name: tutorial
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - git+https://github.com/harupy/mlflow.git@check-where-model-is-logged




